### ISSUE TITLE
I ran into problems

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/registration-form#1]
Hi, so I almost finish the assignment but an issue popped up like this even though my form can function as normal. I don't know why and how to solve it.

![Screen Shot 2020-03-14 at 4 35 05 PM](https://user-images.githubusercontent.com/55094125/76689980-2c7c2780-6612-11ea-89b4-7c97c99d9fec.png)

Here is my html: 
<!DOCTYPE html>
<html lang="en-ca">
<head>
  <meta charset="utf-8">
  <title>Registration form</title>
  <link href="css/modules.css" rel="stylesheet">
  <link href="css/grid.css" rel="stylesheet">
  <link href="css/type.css" rel="stylesheet">
  <link href="css/main.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>

  <section class="max-length gutter pad-t-2 pad-b-2">
    <form method="post" action="https://formspree.io/lamanhmj@gmail.com">
      <div>
        <h1 class="not-bold">Want to go to Mars?</h1>
        <p class="mega">We’re looking for super-awesome human beings who want to make the long trek to Mars for the adventure of a lifetime.</p>
      </div>
      <div>
        <div class="push-0">
          <fieldset class="push-1-2">
            <legend class="not-bold mega italic">Personal details</legend>
          </fieldset>
        </div>
        <div class="grid">
          <div class="padtoright unit xs-1 s-1 m-1 l-1-2 push">
            <label for="name">Name</label>
            <input id="name" name="name" required>
          </div>
          <div class="padtoleft unit xs-1 s-1 m-1 l-1-2 push">
            <label for="age">Age</label>
            <input id="age" type="number" name="age" required>
          </div>
        </div>
        <div class="grid">
          <div class="padtoright unit xs-1 s-1 m-1 l-1-2 push">
            <label for="email">Email</label>
            <input id="email" type="email" name="email" required>
          </div>
          <div class="padtoleft unit xs-1 s-1 m-1 l-1-2 push">
            <label for="fitness">Physical fitness</label>
            <select id="fitness" name="fitness">
              <option>Super-human</option>
              <option>Fit as a fiddle</option>
              <option>Not terribly strong</option>
              <option>A little couch-potato-y</option>
            </select>
          </div>
        </div>
        <div class="push">
          <label for="address">Address</label>
          <textarea id="address" name="address"></textarea>
        </div>
      </div>
      <div class="push">
        <fieldset>
          <legend class="push italic">Mission statement</legend>
        </fieldset>
        <label for="reason">Why do you want to go to Mars?</label>
        <input type="hidden" value="Request to join the mission">
        <textarea id="reason" name="reason"></textarea>
      </div>
      <div class="text-center push-2">
        <button class="btn" type="submit" value="send">Register for the trip!</button>
      </div>
    </form>
  </section>

</body>
</html>

Here is my css: 
html {
  font-family: "Open Sans", sans-serif;
  color: #000;
}

body {
  background-color: #f2f2f2;
}

section {
  background-color: #fff;
}

h1 {
  border-bottom: 1px solid #000;
}

@media only screen and (min-width: 60em) {

  .padtoleft {
    padding-left: .5em;
  }

  .padtoright {
    padding-right: .5em;
  }

}

**Comment by Sam-Le68** [comment]
@muxlowc I forgot to tag you oops

**Comment by muxlowc** [comment]
@Sam-Le68 you need to have post in capital letters:

form method="**POST**" action="https://formspree.io/lamanhmj@gmail.com"

That should fix it!

**Comment by muxlowc** [comment]
@Sam-Le68 

Also, no need to copy/paste your code on here - I can go and see your code from my end :)
